name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          pip install ansible
      
      - name: Create SSH directory if not exist
        run: mkdir -p ~/.ssh

      - name: Add host to known hosts
        run: ssh-keyscan -H 52.63.202.45 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i playbooks/hosts.ini --private-key playbooks/hi.pem -u ubuntu playbooks/install_docker.yml
